### ISSUE TITLE
AUTOMATIC 1111 v 1.7

### ISSUE THREAD

**Issue by goblin776655** [Tps-F/sd-webui-blip2#27]
After update to 1.7 have this error :(

*** Error executing callback ui_tabs_callback for G:\stable-diffusion\webui\extensions\sd-webui-blip2\scripts\main.py
    Traceback (most recent call last):
      File "G:\stable-diffusion\webui\modules\script_callbacks.py", line 169, in ui_tabs_callback
        res += c.callback() or []
      File "G:\stable-diffusion\webui\extensions\sd-webui-blip2\scripts\main.py", line 249, in on_ui_tabs
        modules.generation_parameters_copypaste.create_buttons(
    AttributeError: module 'modules' has no attribute 'generation_parameters_copypaste'

Plz help me!

**Comment by 871699406** [comment]
the module name have change to infotext_utils,so mod it to **modules.infotext_utils.create_buttons** will fix this?

**Comment by Tps-F** [comment]
I'll fix, thanks

**Comment by goblin776655** [comment]
> I'll fix, thanks

Hi again, some news?
Thanks!

**Comment by bu2508dx** [comment]
Replace the file ‘main.py’ in ‘extensions/sd-webui-blip2/scripts/’ with this file:
[new_main.zip](https://github.com/user-attachments/files/16167949/new_main.zip)
